# Use the official Node.js base image
FROM node:14-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the frontend source files into the container
COPY . .

# Install dependencies
RUN npm install

# Build the production version of the React app
RUN npm run build

# Expose the port that your React app listens on
EXPOSE 3000

# Start the React app when the container starts
CMD ["npm", "start"]
