# Server configuration
server:
  port: 8080          # Port on which the backend server will run

# Spring Datasource configuration (modify these settings according to your database)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name?useSSL=false&serverTimezone=UTC
    username: your_database_username
    password: your_database_password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update # Change to 'create' for the first time to create tables

# Spring Security configuration (for authentication and authorization, if applicable)
# Add your security configurations here if you plan to add authentication and authorization

# Logging configuration (optional)
logging:
  level:
    org.springframework: INFO # Change to 'DEBUG' for more detailed logging
    com.example.goaltracker: DEBUG # Set logging level for your application package

# Any other custom configurations or properties
# Add any other configuration specific to your application
