# Server configuration
server:
  port: 8080          # Port on which the backend server will run

# Spring Datasource configuration (modify these settings according to your database)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql-db?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update # Change to 'create' for the first time to create tables

# Spring Security configuration (for authentication and authorization, if applicable)
# Add your security configurations here if you plan to add authentication and authorization

# Logging configuration (optional)
logging:
  level:
    org.springframework: INFO # Change to 'DEBUG' for more detailed logging
    com.example.goaltracker: DEBUG # Set logging level for your application package

# Any other custom configurations or properties
# Add any other configuration specific to your application


# docker cmd: docker pull mysql:latest
# docker run -d --name your-mysql-container -p 3306:3306 -e MYSQL_ROOT_PASSWORD=your-mysql-root-password -e MYSQL_DATABASE=your-database-name mysql:latest

